resource_types:
- name: pr
  type: registry-image
  source:
    repository: pix4d/cogito/pr

resources:
- name: pull-request
  type: pr
  source:
    repository: MMahendravarman/concourse-ci-demo
    access_token: ((github-token))

jobs:
- name: pr-check
  plan:
  - get: pull-request
    trigger: true
    version: every

  - task: build-and-check-coverage
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: maven
          tag: '3.8.3-openjdk-17-slim'
      inputs:
        - name: pull-request
      outputs:
        - name: coverage-output
      params:
        COVERAGE_THRESHOLD: 80
      run:
        path: bash
        args:
          - -exc
          - |
            apt-get update && apt-get install -y jq bc
            cd pull-request
            mvn clean verify
            chmod +x scripts/check_coverage.sh
            ./scripts/check_coverage.sh > ../coverage-output/coverage.txt

  - put: pull-request
    params:
      path: pull-request
      context: ci/concourse-pr-check
      description_file: coverage-output/coverage.txt
