resource_types:
- name: github-pr
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: pr-status
  type: registry-image
  source:
    repository: pix4d/cogito

resources:
- name: pull-request
  type: github-pr
  source:
    repository: MMahendravarman/concourse-ci-demo
    access_token: ((github-token))
    disable_ci_skip: true    

- name: pr-status
  type: pr-status
  source:
    repo: concourse-ci-demo
    owner: MMahendravarman
    access_token: ((github-token))    

jobs:
- name: pr-check
  plan:
  - get: pull-request
    trigger: true
    version: every

  - task: build-and-check-coverage
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: maven
          tag: '3.8.3-openjdk-17-slim'
      inputs:
        - name: pull-request
      outputs:
        - name: coverage-output
      params:
        COVERAGE_THRESHOLD: 80
      run:
        path: bash
        args:
          - -exc
          - |
            apt-get update && apt-get install -y jq bc
            cd pull-request
            mvn clean verify
            chmod +x scripts/check_coverage.sh
            ./scripts/check_coverage.sh > ../coverage-output/coverage.txt
       

    on_success:
      put: pr-status
      inputs: [pull-request]
      params:
        state: success
        
    on_failure:
      put: pr-status
      inputs: [pull-request]
      params:
        state: failure
        